language: python
python:
  - "2.7"
install:
    # Requirements needed for Travis CI
    - pip install coveralls
    - pip install yapf
    - pip install pyflakes
    - pip install pylint==1.5.5
script:
    ./build
after_success:
    coveralls
